version: "3.9"
services:
  api:
    build: { context: ., dockerfile: Dockerfile.serve }
    image: ppe-mlops:serve
    environment:
      - MODEL_BACKEND=yolo
      - MODEL_PATH=yolov8n.pt
      - PORT=8080
    ports: ["8080:8080"]
  ui:
    build: { context: ., dockerfile: Dockerfile.ui }
    image: ppe-mlops:ui
    environment:
      - API_URL=http://api:8080
      - PORT=8501
    ports: ["8501:8501"]
    depends_on: [api]
